# fly.toml para la base de datos PostgreSQL
app = "nitro-api-db"
primary_region = "mad"

[env]
  POSTGRES_PASSWORD = "nitro_password"
  POSTGRES_USER = "nitro_user"
  POSTGRES_DB = "nitro_api"

[processes]
  app = "postgres"

[[services]]
  protocol = "tcp"
  internal_port = 5432
  processes = ["app"]

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "nitro_api_db_data"
  destination = "/var/lib/postgresql/data" 