# fly.toml para Fly Postgres (alta disponibilidad)
app = "nitro-api-postgres"
primary_region = "cdg"

[env]
  POSTGRES_PASSWORD = "nitro_password"
  POSTGRES_USER = "nitro_user"
  POSTGRES_DB = "nitro_api"

[[services]]
  protocol = "tcp"
  internal_port = 5432

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Configuración para alta disponibilidad
[deploy]
  strategy = "immediate"



 