# fly.toml app configuration file generated for nitro-api on 2024-01-20T10:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "nitro-api"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "nitro_api_data"
  destination = "/app/uploads"

[processes]
  app = "node dist/main.js"

[deploy]
  release_command = "npm run migration:run && npm run seed"

[metrics]
  port = 9091
  path = "/metrics" 