[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/docker-entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
APP_DB_PROVIDER = "postgres"

# Configuración para detección automática de PostgreSQL
[services]
[[services.database]]
type = "postgresql"
name = "redfox-db" 