import { DataSource } from 'typeorm';
import { Product, ProductType } from 'src/models/product.entity';
import { Brand } from 'src/models/brand.entity';
import { Category } from 'src/models/category.entity';
import { Tax } from 'src/models/tax.entity';
import { MeasurementUnit } from 'src/models/measurement-unit.entity';
import { DeepPartial } from 'typeorm';

export class ProductsSeed {
  public static async run(dataSource: DataSource): Promise<void> {
    const productRepository = dataSource.getRepository(Product);
    const brandRepository = dataSource.getRepository(Brand);
    const categoryRepository = dataSource.getRepository(Category);
    const taxRepository = dataSource.getRepository(Tax);
    const measurementUnitRepository = dataSource.getRepository(MeasurementUnit);

    // Obtener todas las marcas
    const brands = await brandRepository.find();
    const categories = await categoryRepository.find();
    const ivaTax = await taxRepository.findOne({ where: { code: 'IVA' } });
    const unit = await measurementUnitRepository.findOne({
      where: { code: 'UNIT' },
    });

    if (!ivaTax || !unit) {
      throw new Error('Tax or measurement unit not found');
    }

    const products: DeepPartial<Product>[] = [
      // Smartphones
      {
        name: 'iPhone 15 Pro Max',
        slug: 'iphone-15-pro-max',
        description: 'El iPhone más avanzado con chip A17 Pro y cámara de 48MP',
        sku: 'IP15PM-256-GOLD',
        code: 'PRD-001',
        weight: 0.221,
        width: 0.0767,
        height: 0.1599,
        length: 0.0085,
        brand: brands.find((b) => b.code === 'APPLE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Samsung Galaxy S24 Ultra',
        slug: 'samsung-galaxy-s24-ultra',
        description: 'Flagship Android con S Pen integrado y cámara de 200MP',
        sku: 'SGS24U-512-BLK',
        code: 'PRD-002',
        weight: 0.232,
        width: 0.0789,
        height: 0.1634,
        length: 0.0088,
        brand: brands.find((b) => b.code === 'SAMSUNG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Google Pixel 8 Pro',
        slug: 'google-pixel-8-pro',
        description: 'Smartphone con IA avanzada y cámara de Google',
        sku: 'GP8P-256-BAY',
        code: 'PRD-003',
        weight: 0.213,
        width: 0.0765,
        height: 0.1626,
        length: 0.0087,
        brand: brands.find((b) => b.code === 'GOOGLE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Xiaomi 14 Ultra',
        slug: 'xiaomi-14-ultra',
        description: 'Flagship de Xiaomi con cámara Leica y Snapdragon 8 Gen 3',
        sku: 'XM14U-512-WHT',
        code: 'PRD-004',
        weight: 0.224,
        width: 0.0751,
        height: 0.1614,
        length: 0.0092,
        brand: brands.find((b) => b.code === 'XIAOMI'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'OnePlus 12',
        slug: 'oneplus-12',
        description: 'Performance flagship con carga rápida de 100W',
        sku: 'OP12-256-GRN',
        code: 'PRD-005',
        weight: 0.22,
        width: 0.0754,
        height: 0.1637,
        length: 0.0091,
        brand: brands.find((b) => b.code === 'ONEPLUS'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Laptops
      {
        name: 'MacBook Pro 16" M3 Max',
        slug: 'macbook-pro-16-m3-max',
        description: 'Laptop profesional con chip M3 Max y 32GB RAM',
        sku: 'MBP16-M3M-1TB-SP',
        code: 'PRD-006',
        weight: 2.16,
        width: 0.248,
        height: 0.355,
        length: 0.0168,
        brand: brands.find((b) => b.code === 'APPLE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Dell XPS 15',
        slug: 'dell-xps-15',
        description: 'Laptop premium con pantalla OLED y RTX 4070',
        sku: 'DXPS15-32GB-1TB',
        code: 'PRD-007',
        weight: 1.8,
        width: 0.23,
        height: 0.344,
        length: 0.018,
        brand: brands.find((b) => b.code === 'DELL'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Lenovo ThinkPad X1 Carbon',
        slug: 'lenovo-thinkpad-x1-carbon',
        description: 'Ultrabook empresarial con procesador Intel Core i7',
        sku: 'LTX1C-16GB-512GB',
        code: 'PRD-008',
        weight: 1.12,
        width: 0.224,
        height: 0.314,
        length: 0.015,
        brand: brands.find((b) => b.code === 'LENOVO'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'ASUS ROG Strix G16',
        slug: 'asus-rog-strix-g16',
        description: 'Gaming laptop con RTX 4080 y pantalla 240Hz',
        sku: 'ARGS16-32GB-2TB',
        code: 'PRD-009',
        weight: 2.5,
        width: 0.28,
        height: 0.354,
        length: 0.025,
        brand: brands.find((b) => b.code === 'ASUS_ROG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'MSI Raider GE78 HX',
        slug: 'msi-raider-ge78-hx',
        description: 'Gaming laptop con Intel i9 y RTX 4090',
        sku: 'MRGE78-64GB-4TB',
        code: 'PRD-010',
        weight: 3.0,
        width: 0.29,
        height: 0.38,
        length: 0.028,
        brand: brands.find((b) => b.code === 'MSI'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Auriculares
      {
        name: 'AirPods Pro 2',
        slug: 'airpods-pro-2',
        description: 'Auriculares inalámbricos con cancelación de ruido activa',
        sku: 'APP2-WHT',
        code: 'PRD-011',
        weight: 0.005,
        width: 0.021,
        height: 0.024,
        length: 0.03,
        brand: brands.find((b) => b.code === 'APPLE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Sony WH-1000XM5',
        slug: 'sony-wh-1000xm5',
        description: 'Auriculares over-ear con la mejor cancelación de ruido',
        sku: 'SWHXM5-BLK',
        code: 'PRD-012',
        weight: 0.25,
        width: 0.168,
        height: 0.248,
        length: 0.08,
        brand: brands.find((b) => b.code === 'SONY'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Bose QuietComfort 45',
        slug: 'bose-quietcomfort-45',
        description:
          'Auriculares con tecnología de cancelación de ruido avanzada',
        sku: 'BQC45-BLK',
        code: 'PRD-013',
        weight: 0.24,
        width: 0.17,
        height: 0.25,
        length: 0.075,
        brand: brands.find((b) => b.code === 'BOSE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Sennheiser HD 660S',
        slug: 'sennheiser-hd-660s',
        description: 'Auriculares de estudio con sonido de alta fidelidad',
        sku: 'SHD660S-BLK',
        code: 'PRD-014',
        weight: 0.26,
        width: 0.18,
        height: 0.27,
        length: 0.085,
        brand: brands.find((b) => b.code === 'SENNHEISER'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'JBL Flip 6',
        slug: 'jbl-flip-6',
        description: 'Altavoz portátil Bluetooth resistente al agua',
        sku: 'JFLIP6-BLK',
        code: 'PRD-015',
        weight: 0.55,
        width: 0.068,
        height: 0.178,
        length: 0.068,
        brand: brands.find((b) => b.code === 'JBL'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Componentes de PC
      {
        name: 'Intel Core i9-14900K',
        slug: 'intel-core-i9-14900k',
        description: 'Procesador de 24 núcleos con overclocking desbloqueado',
        sku: 'ICI9-14900K',
        code: 'PRD-016',
        weight: 0.042,
        width: 0.0375,
        height: 0.0375,
        length: 0.0045,
        brand: brands.find((b) => b.code === 'INTEL'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'AMD Ryzen 9 7950X',
        slug: 'amd-ryzen-9-7950x',
        description: 'Procesador de 16 núcleos con arquitectura Zen 4',
        sku: 'AR9-7950X',
        code: 'PRD-017',
        weight: 0.038,
        width: 0.04,
        height: 0.04,
        length: 0.004,
        brand: brands.find((b) => b.code === 'AMD'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'NVIDIA RTX 4090',
        slug: 'nvidia-rtx-4090',
        description: 'Tarjeta gráfica más potente con 24GB GDDR6X',
        sku: 'NRTX4090-FE',
        code: 'PRD-018',
        weight: 2.2,
        width: 0.304,
        height: 0.137,
        length: 0.061,
        brand: brands.find((b) => b.code === 'NVIDIA'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Kingston Fury DDR5 32GB',
        slug: 'kingston-fury-ddr5-32gb',
        description: 'Memoria RAM DDR5 de alta velocidad para gaming',
        sku: 'KF32GB-6000',
        code: 'PRD-019',
        weight: 0.045,
        width: 0.133,
        height: 0.032,
        length: 0.004,
        brand: brands.find((b) => b.code === 'KINGSTON'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Samsung 990 Pro 2TB',
        slug: 'samsung-990-pro-2tb',
        description: 'SSD NVMe de alta velocidad con 2TB de capacidad',
        sku: 'S990P-2TB',
        code: 'PRD-020',
        weight: 0.009,
        width: 0.08,
        height: 0.022,
        length: 0.1,
        brand: brands.find((b) => b.code === 'SAMSUNG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Periféricos Gaming
      {
        name: 'Razer DeathAdder V3 Pro',
        slug: 'razer-deathadder-v3-pro',
        description: 'Mouse gaming inalámbrico con sensor de 30K DPI',
        sku: 'RDV3P-WHT',
        code: 'PRD-021',
        weight: 0.063,
        width: 0.068,
        height: 0.127,
        length: 0.044,
        brand: brands.find((b) => b.code === 'RAZER'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Logitech G Pro X Superlight',
        slug: 'logitech-g-pro-x-superlight',
        description: 'Mouse ultraligero para gaming competitivo',
        sku: 'LGPXSL-BLK',
        code: 'PRD-022',
        weight: 0.063,
        width: 0.062,
        height: 0.125,
        length: 0.039,
        brand: brands.find((b) => b.code === 'LOGITECH'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'SteelSeries Apex Pro',
        slug: 'steelseries-apex-pro',
        description: 'Teclado mecánico con switches ópticos ajustables',
        sku: 'SSAP-BLK',
        code: 'PRD-023',
        weight: 0.908,
        width: 0.44,
        height: 0.035,
        length: 0.14,
        brand: brands.find((b) => b.code === 'STEELSERIES'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Corsair K100 RGB',
        slug: 'corsair-k100-rgb',
        description: 'Teclado premium con switches Cherry MX y teclas macro',
        sku: 'CK100-BLK',
        code: 'PRD-024',
        weight: 1.2,
        width: 0.47,
        height: 0.04,
        length: 0.16,
        brand: brands.find((b) => b.code === 'CORSAIR'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Razer BlackShark V2 Pro',
        slug: 'razer-blackshark-v2-pro',
        description: 'Auriculares gaming con micrófono removible',
        sku: 'RBSV2P-BLK',
        code: 'PRD-025',
        weight: 0.32,
        width: 0.19,
        height: 0.2,
        length: 0.085,
        brand: brands.find((b) => b.code === 'RAZER'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Cámaras
      {
        name: 'Canon EOS R5',
        slug: 'canon-eos-r5',
        description: 'Cámara mirrorless full-frame con 8K video',
        sku: 'CER5-BLK',
        code: 'PRD-026',
        weight: 0.738,
        width: 0.138,
        height: 0.098,
        length: 0.088,
        brand: brands.find((b) => b.code === 'CANON'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Nikon Z9',
        slug: 'nikon-z9',
        description: 'Cámara mirrorless profesional con sensor de 45.7MP',
        sku: 'NZ9-BLK',
        code: 'PRD-027',
        weight: 1.34,
        width: 0.149,
        height: 0.119,
        length: 0.09,
        brand: brands.find((b) => b.code === 'NIKON'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Sony A7R V',
        slug: 'sony-a7r-v',
        description: 'Cámara mirrorless con sensor de 61MP y IA avanzada',
        sku: 'SA7RV-BLK',
        code: 'PRD-028',
        weight: 0.723,
        width: 0.131,
        height: 0.096,
        length: 0.084,
        brand: brands.find((b) => b.code === 'SONY'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Monitores
      {
        name: 'LG 27GP950-B',
        slug: 'lg-27gp950-b',
        description: 'Monitor gaming 4K 144Hz con FreeSync Premium Pro',
        sku: 'L27GP950-BLK',
        code: 'PRD-029',
        weight: 6.8,
        width: 0.614,
        height: 0.365,
        length: 0.24,
        brand: brands.find((b) => b.code === 'LG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Samsung Odyssey G9',
        slug: 'samsung-odyssey-g9',
        description: 'Monitor ultrawide curvo 49" 240Hz',
        sku: 'SOG9-49',
        code: 'PRD-030',
        weight: 13.2,
        width: 1.147,
        height: 0.369,
        length: 0.38,
        brand: brands.find((b) => b.code === 'SAMSUNG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Tablets
      {
        name: 'iPad Pro 12.9" M2',
        slug: 'ipad-pro-12-9-m2',
        description:
          'Tablet profesional con chip M2 y pantalla Liquid Retina XDR',
        sku: 'IPP12-M2-256GB',
        code: 'PRD-031',
        weight: 0.682,
        width: 0.214,
        height: 0.28,
        length: 0.0064,
        brand: brands.find((b) => b.code === 'APPLE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Samsung Galaxy Tab S9 Ultra',
        slug: 'samsung-galaxy-tab-s9-ultra',
        description: 'Tablet Android de 14.6" con S Pen incluido',
        sku: 'SGTS9U-256GB',
        code: 'PRD-032',
        weight: 0.732,
        width: 0.208,
        height: 0.326,
        length: 0.0055,
        brand: brands.find((b) => b.code === 'SAMSUNG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Smartwatches
      {
        name: 'Apple Watch Series 9',
        slug: 'apple-watch-series-9',
        description: 'Smartwatch con chip S9 y monitor de salud avanzado',
        sku: 'AWS9-45MM-ALUM',
        code: 'PRD-033',
        weight: 0.051,
        width: 0.045,
        height: 0.045,
        length: 0.013,
        brand: brands.find((b) => b.code === 'APPLE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Samsung Galaxy Watch 6 Classic',
        slug: 'samsung-galaxy-watch-6-classic',
        description: 'Smartwatch con bisel rotativo y Wear OS',
        sku: 'SGWC6-47MM',
        code: 'PRD-034',
        weight: 0.059,
        width: 0.047,
        height: 0.047,
        length: 0.014,
        brand: brands.find((b) => b.code === 'SAMSUNG'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Consolas Gaming
      {
        name: 'PlayStation 5',
        slug: 'playstation-5',
        description: 'Consola de nueva generación con SSD ultra rápido',
        sku: 'PS5-DISC',
        code: 'PRD-035',
        weight: 4.5,
        width: 0.39,
        height: 0.104,
        length: 0.26,
        brand: brands.find((b) => b.code === 'SONY'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Xbox Series X',
        slug: 'xbox-series-x',
        description: 'Consola más potente con 12 TFLOPS de rendimiento',
        sku: 'XSX-1TB',
        code: 'PRD-036',
        weight: 4.45,
        width: 0.151,
        height: 0.151,
        length: 0.301,
        brand: brands.find((b) => b.code === 'MICROSOFT'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Almacenamiento
      {
        name: 'Western Digital Black SN850X 2TB',
        slug: 'western-digital-black-sn850x-2tb',
        description: 'SSD NVMe de alta velocidad para gaming',
        sku: 'WDSN850X-2TB',
        code: 'PRD-037',
        weight: 0.008,
        width: 0.08,
        height: 0.022,
        length: 0.1,
        brand: brands.find((b) => b.code === 'WESTERN_DIGITAL'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },
      {
        name: 'Seagate FireCuda 530 2TB',
        slug: 'seagate-firecuda-530-2tb',
        description: 'SSD NVMe con velocidades de hasta 7300 MB/s',
        sku: 'SFC530-2TB',
        code: 'PRD-038',
        weight: 0.009,
        width: 0.08,
        height: 0.022,
        length: 0.1,
        brand: brands.find((b) => b.code === 'SEAGATE'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.TANGIBLE,
      },

      // Servicios
      {
        name: 'Servicio de Mantenimiento PC',
        slug: 'servicio-mantenimiento-pc',
        description: 'Servicio de mantenimiento preventivo para computadoras',
        sku: 'SERV-MANT-PC',
        code: 'PRD-039',
        brand: brands.find((b) => b.code === 'GENERIC'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.SERVICE,
      },
      {
        name: 'Servicio de Reparación Smartphone',
        slug: 'servicio-reparacion-smartphone',
        description: 'Servicio de reparación para smartphones y tablets',
        sku: 'SERV-REP-SMART',
        code: 'PRD-040',
        brand: brands.find((b) => b.code === 'GENERIC'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.SERVICE,
      },
      {
        name: 'Servicio de Instalación Software',
        slug: 'servicio-instalacion-software',
        description: 'Instalación y configuración de software especializado',
        sku: 'SERV-INST-SOFT',
        code: 'PRD-041',
        brand: brands.find((b) => b.code === 'GENERIC'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.SERVICE,
      },
      {
        name: 'Servicio de Recuperación de Datos',
        slug: 'servicio-recuperacion-datos',
        description: 'Recuperación de datos de discos dañados',
        sku: 'SERV-REC-DATOS',
        code: 'PRD-042',
        brand: brands.find((b) => b.code === 'GENERIC'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.SERVICE,
      },
      {
        name: 'Servicio de Consultoría IT',
        slug: 'servicio-consultoria-it',
        description: 'Consultoría en tecnologías de la información',
        sku: 'SERV-CONS-IT',
        code: 'PRD-043',
        brand: brands.find((b) => b.code === 'GENERIC'),
        category: categories.find((c) => c.slug === 'ELEC'),
        tax: ivaTax,
        measurement_unit: unit,
        is_active: true,
        type: ProductType.SERVICE,
      },
    ];

    for (const product of products) {
      const existingProduct = await productRepository.findOne({
        where: { sku: product.sku },
      });

      if (!existingProduct) {
        await productRepository.save(product);
      }
    }
  }
}
